language: scala
scala:
  - 2.10.4
jdk:
  - openjdk7
sudo: false
before_install:
  - git clone --branch=v4.3.2 --depth=1 https://git01.codeplex.com/z3 z3-repo
  - cd z3-repo
  - python scripts/mk_make.py --prefix=z3-dist
  - mkdir -p build/z3-dist/lib/python2.7/site-packages
  - cd build
  - make
  - make install
  - cd ../../
  - cp -r z3-repo/build/z3-dist z3/4.3-unix-64b/
script:
  - sbt -jvm-opts travis/jvmopts.test package
  - sbt -jvm-opts travis/jvmopts.test test
