language: scala
scala:
  - 2.10.4
jdk:
  - openjdk7
sudo: false
before_install:
  # Download the source for the v.4.3.2 tag of Z3 from Codeplex:
  - curl 'https://download-codeplex.sec.s-msft.com/Download/SourceControlFileDownload.ashx?ProjectName=z3&changeSetId=cee7dd39444c9060186df79c2a2c7f8845de415b' > z3-src.zip
  - unzip z3-src.zip -d z3-repo
  # - git clone --branch=v4.3.2 --depth=1 https://git.codeplex.com/z3 z3-repo
  - cd z3-repo
  - python scripts/mk_make.py --prefix=z3-dist
  - mkdir -p build/z3-dist/lib/python2.7/dist-packages
  - cd build
  - make
  - make install
  - cd ../../
  - mkdir z3
  - cp -r z3-repo/build/z3-dist z3/4.3-unix-64b/
script:
  - sbt -jvm-opts travis/jvmopts.test package
  - sbt -jvm-opts travis/jvmopts.test test
